# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp evalCpp
#'@useDynLib fastBayesReg, .registration=TRUE
NULL

#'@title Simulate data from the logistic regression model
#'@param n sample size
#'@param p number of candidate predictors
#'@param q number of nonzero predictors
#'@param beta_size effect size of beta coefficients
#'@return a list objects consisting of the following components
#'\describe{
#'\item{delta}{vector of n outcome variables}
#'\item{X}{n x p matrix of candidate predictors}
#'\item{betacoef}{vector of p regression coeficients}
#'\item{R2}{R-squared indicating the proportion of variation explained by the predictors}
#'}
#'@author Jian Kang <jiankang@umich.edu>
#'@examples
#'dat <- sim_linear_reg(100,100,0.5,c(1,-1,1))
#'@export
sim_linear_reg <- function(n, p, R2, beta_nonzero) {
    .Call(`_fastBayesReg_sim_linear_reg`, n, p, R2, beta_nonzero)
}

